WebApp/WebApp/Models/MsgData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class MsgData
    {
        public string AppToken { get; set; }
        public string UserKey { get; set; }
        public string Message { get; set; }
    }
}

WebApp/WebApp/Controllers/SendController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class SendController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SomeResult()
        {
            MsgData messageData = new MsgData();
            return View(messageData);
        }

        
        [HttpPost]
        public ActionResult SomeResult([FromForm] MsgData messageData)
        {           

            using (var client = new WebClient())
            {
                var parameters = new NameValueCollection
                {
                    { "token", messageData.AppToken },
                    { "user", messageData.UserKey },
                    { "message", messageData.Message }
                };

                client.UploadValues("https://api.pushover.net/1/messages.json", parameters);
            }           

            return Redirect("~/");            
        }               
    }
}

WebApp/WebApp/Pages/Contacts.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class ContactsModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

WebApp/WebApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApp/WebApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

WebApp/WebApp/Pages/Contacts.cshtml

@page

@model ContactsModel
@{
    ViewData["Title"] = "Contacts";
}

<h1>@ViewData["Title"]</h1>

<address >
    <p><strong>Леонид Коноплин</strong></p>
    <ul>
        <li>
            <a href="mailto:konoplin.l@mail.ru">konoplin.l@mail.ru</a>
        </li>
        <li>
            <a href="tel:8-918-151-74-47">8-918-151-74-47</a>
        </li>
        <li>
            <a href="https://www.linkedin.com/in/%D0%BB%D0%B5%D0%BE%D0%BD%D0%B8%D0%B4-%D0%BA%D0%BE%D0%BD%D0%BE%D0%BF%D0%BB%D0%B8%D0%BD-316035126">LinkedIn</a>
        </li>
        <li>
            <a href="https://github.com/777LK777">GitHub</a>
        </li>
    </ul>
</address>

WebApp/WebApp/Pages/Index.cshtml
@page
@using  WebApp.Models

    @model WebApp.Models.MsgData
    @{
        ViewData["Title"] = "Home page";
    }
   
    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
    </div>
    <div id="send-place" >
        <hr />
        <form s id="SendForm" asp-action="SomeResult" asp-controller="Send" method="post">

            <table style="width:100%; align-self:center">
            <tr>
                <td class="left-column">User Key:</td>
                <td class="center-column"><input asp-for="UserKey" class="keys-field" required /></td>
                <td class="right-column">&nbsp;</td>
            </tr>
                <tr>
                    <td style="font-size:4px">&nbsp;</td>
                </tr>
            <tr>
                <td class="left-column">API Token:</td>
                <td class="center-column"><input asp-for="AppToken" class="keys-field" required /></td>
                <td class="center-column">&nbsp;</td>
            </tr>
                <tr>
                    <td colspan="3">
                        <hr />
                    </td>
                </tr>
            <tr valign="top">
                <td class="left-column">Message:</td>
                <td class="center-column">
                    <textarea asp-for="Message" class="msg-area" maxlength="512" required></textarea>
                </td>
                <td class="center-column"><input type="submit" id="SendBTN" value="SEND" /></td>
            </tr>
            </table>
            
        </form>
    </div>
    



WebApp/WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Send API</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/css/site.css" rel="stylesheet" type="text/css" />
        <link rel="shortcut icon" href="https://777lk777.github.io/Title.png" type="image/png" />
    </environment>

    @*<environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>*@    
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" ><strong>Send API</strong></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-page="/Index">SEND</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-page="/Contacts">Contacts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Send To Pushover Web API | <a asp-page="/Contacts">Contacts</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>